name: Storybook Deployment

on:
  pull_request:
    branches:
      - main

jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-storybook

      - name: Install dependencies
        run: yarn install

      - name: Build Storybook
        run: yarn build-storybook

      - name: Build App
        run: yarn build

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        if: github.event_name == 'pull_request' # PR에서만 Chromatic 실행
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment PR with Storybook URL
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: "🚀 Storybook 링크: ${{ steps.chromatic.outputs.storybookUrl }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
